name: Monthly Model Retraining

on:
  schedule:
    # Run on the first day of each month at 00:00 UTC
    - cron: '0 0 1 * *'

jobs:
  monthly-retrain:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository to the runner
      - name: Check out repo
        uses: actions/checkout@v2

      # 2) Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the required Python version

      # 3) Install Python dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Update training_timeframe.csv with previous month's timeframe
      - name: Update training timeframe
        run: |
          python - <<'EOF'
import datetime, calendar
from dateutil.relativedelta import relativedelta

# Get the first day of the current month (resetting time to 00:00:00)
now = datetime.datetime.now()
this_month_start = now.replace(day=1, hour=0, minute=0, second=0, microsecond=0)

# Calculate the start of the previous month
last_month_start = this_month_start - relativedelta(months=1)

# Determine the number of days in the previous month to set the correct end date
last_month_days = calendar.monthrange(last_month_start.year, last_month_start.month)[1]
# Set the end of the previous month to the last day at 23:59:59
last_month_end = last_month_start.replace(day=last_month_days, hour=23, minute=59, second=59)

# Write header and new timeframe record into the CSV file with the desired format
with open('ML_model/ML_model_retraining/training_timeframe.csv', 'w', encoding='utf-8') as f:
    f.write('id;start_date;end_date\n')
    f.write(f'1;{last_month_start.strftime("%d.%m.%Y %H:%M:%S")};{last_month_end.strftime("%d.%m.%Y %H:%M:%S")}\n')
EOF

      # 5) Retrain the model by running model_training_retrain.py
      - name: Retrain model
        run: |
          python ML_model/ML_model_retraining/model_training_retrain.py

      # 6) Register the model by running model_registration_retrain.py
      - name: Register model
        run: |
          python ML_model/ML_model_retraining/model_registration_retrain.py
