name: Monthly Model Retraining

on:
  schedule:
    # Run on the first day of each month at 00:00 UTC
    - cron: '0 0 1 * *'
  workflow_dispatch:      # manual run of WF for testing

jobs:
  monthly-retrain:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository to the runner
      - name: Check out repo
        uses: actions/checkout@v2

      # 2) Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the required Python version

      # 3) Install Python dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Update training timeframe by running update_training_timeframe.py
      - name: Update training timeframe
        run: |
          python ML_model/ML_model_retraining/training_timeframe_update.py

      # 5) Retrain the model
      - name: Retrain model
        run: |
          python ML_model/ML_model_retraining/model_training_retrain.py

      # 6) Register the model
      - name: Register model
        run: |
          python ML_model/ML_model_retraining/model_registration_retrain.py
